### ISSUE TITLE
1년이 넘는 시간이 흘렀습니다!

### ISSUE THREAD

**Issue by nesffer** [if-Team/atom-live2d#3]
### 아직도 잘 작동하네요!

![2018-04-02 04 51 29](https://user-images.githubusercontent.com/7542558/38176879-f5bcf4ac-3631-11e8-9115-7934d69b6e0f.png)

**Comment by HelloWorld017** [comment]
:+1:

**Comment by nesffer** [comment]
너무해 ㅋㅋㅋㅋㅋㅋㅋ 말 한 마디 없엉
